### ISSUE TITLE
how i cant run multple instance

### ISSUE THREAD

**Issue by gildastema** [danielcardeenas/sulla#108]
how i cant run multple instance

**Comment by smashah** [comment]
Well you could just copy the running code into another folder and run it. That way it creates a new session folder.

Although I've never tried this myself im pretty sure it would work as I usually have a normal WhatsApp web instance running for another number while I'm working with sulla.

**Comment by gildastema** [comment]
Tks. but isnt a cool solution.

**Comment by smashah** [comment]
You could try my solution on a skateboard then it may be cool enough 😂

**Comment by gildastema** [comment]
> You could try my solution on a skateboard then it may be cool enough
i saw your hotfix  nice job @smashah

**Comment by cyberiums** [comment]
Is there a way to put this on load balancer?
