### ISSUE TITLE
Trying to get group members id but keep getting error

### ISSUE THREAD

**Issue by amajai** [danielcardeenas/sulla#110]
What did I do wrong? This was the code I used.
```
const sulla = require('sulla');

sulla.create().then(client => start(client));

function start(client) {
  client
    .getGroupMembers('G7XXXXXXXXXXXXXX')
    .then(res => console.log(res))
    .then(err => console.log(err));
}
```
The error
```
 Error: Evaluation failed: TypeError: Cannot read property 'participants' of undefined
```

**Comment by vasani-arpit** [comment]
Judging by the the error. the ID of the group you are providing is wrong. Please try the original method on Devtools ```WAPI.getGroupMetadata(id,callback)``` there is also ```WAPI.getGroupMetadata(callback)```

**Comment by amajai** [comment]
@vasani-arpit How do you use it? It like this?

```
function start(client) {
  client
    WAPI.getGroupMetadata(id,callback)
    .then(res => console.log(res))
    .then(err => console.log(err));
}
```

**Comment by vasani-arpit** [comment]
I don't know how you can do that with ts. but the [underlying library](https://github.com/danielcardeenas/sulla/tree/master/src/lib) which is being used in this repo does that using this `getGroupParticipantIDs` method. 

Full snippet would be as following

```
WAPI.getGroupParticipantIDs("91XXXX-XXXX05059@g.us",(...arguments)=>{console.log(arguments)})
```

**Comment by robertsLando** [comment]
Actually you have two options: 

```js
// Get group members
await client.getGroupMembers(groupId);

// Get group members ids
await client.getGroupMembersIds(groupId);
```
