### ISSUE TITLE
Anyway I could send message to new number(Unsaved contact)

### ISSUE THREAD

**Issue by amajai** [danielcardeenas/sulla#114]
First of all, great work on the app.
I tried sending messages to couple of new numbers with this:
```
function start(client) {
  for (let num of main) {
    client.sendText(`${num}@c.us`, text);
  }
}
```
None of the new contacts got the messages. Please help!!
Also, I noticed it only sends to all contacts that are already chat page. Is there something in the code i need to change?
Edit: Fix typos

**Comment by vasani-arpit** [comment]
Does your `${num}` include country code?

**Comment by andretasty** [comment]
Any result on it?

**Comment by amajai** [comment]
@andretasty Nope, still having the problem

**Comment by amajai** [comment]
@vasani-arpit yes I just tried it again and it didn't work. The receiver is registered in WhatsApp and it is also shown on 'select contact' section that the number is valid. However, I didn't use the WAPI class. How do I use it, it might make a difference.

**Comment by andretasty** [comment]
@amajai did you tested with WAPI class?

**Comment by vasani-arpit** [comment]
@amajai @andretasty 

As you know the underlying library which us being used is [wapi.js](https://github.com/danielcardeenas/sulla/tree/master/src/lib) (which I use in my wbot repo as well). I am yet to explore TypeScript so I prefer same old JS debugging.

In which I'd run web.whatsapp in normal chrome and inject wapi.js using snippet in DevTools. Once it is injected I can use the functions it provides like wapi.sendMessage2 which is being used by this library but via TypeScript.

Now, you can do all this programmatically, that's what exactly sulla does.

**Comment by andretasty** [comment]
When i try to send a message to new chat, and give a console.log on sendText, node give me this line: Promise { <pending> }. What is this?

**Comment by vasani-arpit** [comment]
It is returning a promise. You need to add `.then()` and `.catch()` to get the result when it completes. for more you can check https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

**Comment by andretasty** [comment]
is that the problem? Every time that i need to send a message, before i need to open a chat to the contact receive. here is my actual code

```
// import { create, Whatsapp } from 'sulla';
const sulla = require('sulla');
const express = require('express');

const app = express();

sulla.create().then(client => start(client));

function start(client) {
app.get("/:numero/:msg/", function(req, res){
      client.sendText(req.params.numero + '@c.us',req.params.msg);
      res.sendFile(__dirname + '/html/index.html');
      })
}
app.listen(8090, function(){
      console.log("servidor rodando");
  });
```

**Comment by vasani-arpit** [comment]
Keep express aside. Just for the testing purpose and try this

```js
const sulla = require('sulla');
const numero = '12345678900'

sulla.create().then(client => start(client));

function start(client) {
      client.sendText(numero+'@c.us', '👋 Hello from sulla!');
}
```

If this works then you can think about adding express. If it doesn't then there is something wrong with sulla.

**Comment by andretasty** [comment]
Still doesn't work :/. Sulla only sends message when the contact is in chat tab

**Comment by vasani-arpit** [comment]
There could be something wrong with sulla. You can use [original one](https://github.com/mukulhase/WebWhatsapp-Wrapper) or modify [wbot](https://github.com/vasani-arpit/WBOT)

**Comment by vasani-arpit** [comment]
On second thought. If you can change this [line](https://github.com/danielcardeenas/sulla/blob/master/src/api/whatsapp.ts#L45) to `sendMessage2` then it could work.

**Comment by amajai** [comment]
Interesting solution. Will try changing the line first. If it doesn't work out, I'll try the wbot since I'm struggling to make the original work for me.

**Comment by andretasty** [comment]
When i inject wapi.js on web.whatsapp, i get false response when the chat isn't started.

**Comment by amajai** [comment]
@vasani-arpit Unfortunately, changing it to `sendMessage2` didn't make a difference. I'm guessing same will happen with wbot since the underlying library is wapi.js. Oh well, looks like its not possible after all. Thanks for the help though.

**Comment by andretasty** [comment]
I'm trying to find another solution. If i found, i will post here

**Comment by amajai** [comment]
@andretasty Much appreciated you can. I'll do the same as well.

**Comment by austonpramodh** [comment]
any solutions?

**Comment by priteshpmehta** [comment]
> Keep express aside for the testing purpose and try this
> 
> ```js
> const sulla = require('sulla');
> const numero = '12345678900'
> 
> sulla.create().then(client => start(client));
> 
> function start(client) {
>       client.sendText(numero+'@c.us', '👋 Hello from sulla!');
> }
> ```
> 
> If this works then you can think about adding express. If it doesn't then there is something wrong with sulla.

Did any one find solution for this? I am getting **ReferenceError: WAPI is not defined** error message.

**Comment by danielcardeenas** [comment]
Plase update to new version

To send a message to a contact (non-group) just type the number

```typescript
client.sendText('555555555555@c.us', 'Direct message');
```

On a regular message received do a `console.log(message)` to and check the `from` property
