### ISSUE TITLE
Send message to new contact

### ISSUE THREAD

**Issue by andretasty** [danielcardeenas/sulla#115]
Hello, i'm trying to send message to a phone number that isn't in my chat tab, a new number. The number that is in international format, but i cant send. Is anyone with the same problem. Below is my code:

```
// import { create, Whatsapp } from 'sulla';
const sulla = require('sulla');
const express = require('express');

const app = express();

sulla.create().then(client => start(client));

function start(client) {
app.get("/:numero/:msg/", function(req, res){
      client.sendText(req.params.numero + '@c.us',req.params.msg);
      res.sendFile(__dirname + '/html/index.html');
      })
}
app.listen(8090, function(){
      console.log("servidor rodando");
  });
```

**Comment by lfcoelho1** [comment]
I have the same problem

**Comment by rfscheidt** [comment]
Any response?

**Comment by priteshpmehta** [comment]
Hey @andretasty , did you find any solution for this?

**Comment by danielcardeenas** [comment]
Plase update to new version

To send a message to a contact (non-group) just type the number

```typescript
client.sendText('555555555555@c.us', 'Direct message');
```

On a regular message received do a `console.log(message)` to and check the `from` propertie
