### ISSUE TITLE
Will whatsapp block me?

### ISSUE THREAD

**Issue by diegocamy** [danielcardeenas/sulla#119]
Will WhatsApp block my number if I use sulla?

**Comment by vasani-arpit** [comment]
Yes. There are chances of that if you send message same message over and over to different people. 

but if you just reply on incoming message then chances are less.

**Comment by smashah** [comment]
Yes please think of all of us before spamming users with messages.

**Comment by danielcardeenas** [comment]
If you start spamming, yes! Use responsibly
