### ISSUE TITLE
Anyways to subscribe to last seen of contact?

### ISSUE THREAD

**Issue by austonpramodh** [danielcardeenas/sulla#121]
Are any apis available for getting contact online updates?.

**Comment by vasani-arpit** [comment]
Do you mean like stories of the user or a state like online-offline ?

**Comment by LongyaZhao** [comment]
Personally think that timing is obtained by the method of getAllContacts

**Comment by vasani-arpit** [comment]
I have seen it working https://github.com/alfred82santa/whalesong 

I don't know much about python but it seems to allow you to add online/offline listener on a particular contact. Let me know if it works for you.

**Comment by austonpramodh** [comment]
Sure... thank you so much. I will test it out this weekend.. and pingback. Thank you...  


any possibilities to implement this feature on the Sulla framework. Would love to contribute but not able to find anyways...

**Comment by vasani-arpit** [comment]
I have been looking for same functionality for my repo but python is out of my reach and JS pattern followed in that repo flew top of my mind so I have been looking for someone who knows the best of both wolds to understand it then I can implement it in sulla or wbot.

**Comment by smashah** [comment]
May be related to this https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/535

**Comment by austonpramodh** [comment]
> May be related to this [mukulhase/WebWhatsapp-Wrapper#535](https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/535)

[comment](https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/535#issuecomment-546171099)

this does work. I am still finding a way to subscribe to the changes.

**Comment by smashah** [comment]
@austonpramodh I think you'll need to get pupeteer to select a conversation, wait for a few seconds, then use ```.previewMessage.__x_ephemeralStartTimestamp```

**Comment by danielcardeenas** [comment]
Check README function `onAck()`
