### ISSUE TITLE
Decryption (picture, audio) problem

### ISSUE THREAD

**Issue by LongyaZhao** [danielcardeenas/sulla#122]
Hello, great god. I switched to your framework. You can get Store.CryptoLib.decryptE2EMedia(e, t, n, r, a). Personally think that this can decrypt pictures or audio. I tried to crack. Guess the message obtained with Store.Chat.get(id).msgs. /**
          * e may be __x_type
          * t ArrayBuffer not detected
          * n __x_mediaKey
          * r may be __x_mimetype
          * a may be __x_mediaKeyTimestamp
          */
I don't know if God is free to decrypt it.

**Comment by smashah** [comment]
@LongyaZhao https://github.com/smashah/sulla/blob/master/README.md#decrypting-media

**Comment by LongyaZhao** [comment]
@smashah Thank you

**Comment by LongyaZhao** [comment]
@smashah Great God, I use your Sulla-hotfix to receive the image after transferring to base64, it does not show up.

**Comment by LongyaZhao** [comment]
@smashah Hello God, ask you a question. I can get the url of the avatar. How to get it?

**Comment by smashah** [comment]
@LongyaZhao on the contact object you can access an image url that works via ```profilePicThumbObj.eurl```

**Comment by LongyaZhao** [comment]
@smashah God, thank you. Please take my knees. I don't know if God has done whatsapp on the mobile side?

**Comment by danielPrando** [comment]
the image gets corrupted after decrypt, can you tell me what it can be?
