### ISSUE TITLE
multi users / connection

### ISSUE THREAD

**Issue by GlauberF** [danielcardeenas/sulla#125]
How to manage, save multiple instance of whatsapp web, for more than one user / number?

**Comment by austonpramodh** [comment]
you could change the user data directory... but unfortunately, it's not exposed out of the sulla library.


![image](https://user-images.githubusercontent.com/5049050/67583027-66828500-f768-11e9-82e7-3bf22db0c06f.png)


you can find it here..

**Comment by smashah** [comment]
Maybe it's be a good idea to have a new version that takes in some sort of I'd which then creates a new sessions directory with that id.

**Comment by smashah** [comment]
@austonpramodh @GlauberF  please try this and let me know if it works for you thanks

https://github.com/smashah/sulla#managing-multiple-sessions-at-once

**Comment by danielcardeenas** [comment]
Just exposed the session name as a parameter in the new version so you can create multiple instances:

```typescript
const sulla = require("sulla");
sulla.create('robot-1').then(client => ...);
sulla.create('robot-2').then(client => ...);
```

Remember to update sulla
