### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by armandochavez** [danielcardeenas/sulla#128]
Hola cómo puedo crear un menú y de acuerdo lo que le selección le haga otra pregunta diferente

**Comment by armandochavez** [comment]
Ejemplo 
....menú...
1.-dni
2.-nombre 
 
Y si envía 1 que le diga que ponga su número de Dni

**Comment by danielcardeenas** [comment]
Esto depende de como tu lo quieras manejar. Ya es programación de tu parte.
Lo que buscas es de alguna forma memorizar que el usuario esta en 'x' paso del proceso del menú.
Cuando te conteste con un mensaje averiguar en que paso esta y contestarle de acuerdo.

Suerte!
