### ISSUE TITLE
how to install correctly

### ISSUE THREAD

**Issue by gabrieru** [danielcardeenas/sulla#13]
i followed steps:
install node.js 
create instance npm init
install sulla
create index.js
paste code to index.js
run node index.js

error happens, i am missing something but i dont know exactly 
![image](https://user-images.githubusercontent.com/11533330/60034044-5ac66b00-966f-11e9-89c8-d2ce7e978237.png)

someone who installed this can help me please? thanks

**Comment by djdnl13** [comment]
This works for me with `node index.js`

```
//import { create, Whatsapp } from 'sulla';
const create = require("sulla").create;
const Whatsapp = require("sulla").Whatsapp;
create().then(client => start(client));

function start(client) {
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
    }
  });
}
```

**Comment by gabrieru** [comment]
this runs! thanks!1

El mar., 25 de jun. de 2019 a la(s) 21:25, Daniel Lozano (notifications@github.com<mailto:notifications@github.com>) escribió:

This works for me with node index.js

//import { create, Whatsapp } from 'sulla';

const create = require("sulla").create;

const Whatsapp = require("sulla").Whatsapp;

create().then(client => start(client));



function start(client) {

  client.onMessage(message => {

    if (message.body === 'Hi') {

      client.sendText(message.from, '👋 Hello from sulla!');

    }

  });

}

**Comment by danielcardeenas** [comment]
The example is implying the use of Typescript. I'm going to add a plain javascript example!

**Comment by danielct59** [comment]
#danielcardeenas 

please help me to install in a practical way in linux debian 8 ... if I mention I will contribute financially with the project

I need to inform me which dependencies I must install to run and how should I proceed ... I am looking forward ... thanks

**Comment by danielcardeenas** [comment]
Just install node.js
