### ISSUE TITLE
Getting blur image after converting from Base64 to png/jpg

### ISSUE THREAD

**Issue by sagarsaini3993** [danielcardeenas/sulla#140]
Hi @danielcardeenas , I'm receiving Base64 whenever any user sends me an image. If I'm converting that Base64 to image file, the converted image is very small in size and blurry. Can you suggest anything so that I can get original image back.

**Comment by smashah** [comment]
@sagarsaini3993 that is only the thumbnail before pressing download. The whole age needs to be decrypted from the link in the message payload.

**Comment by sagarsaini3993** [comment]
@danielcardeenas  ok Thanks.
