### ISSUE TITLE
ReferenceError: WAPI is not defined while sending Text to existing number

### ISSUE THREAD

**Issue by priteshpmehta** [danielcardeenas/sulla#149]
```
const sulla = require('sulla');

sulla.create().then(client => start(client));

function start(client) {
      client.sendText('32131544789@c.us', '👋 Hello from sulla!');
}
```
@danielcardeenas @ZagButNoZig  ??

**Comment by vasani-arpit** [comment]
web.whatsapp got updated yesterday.  WAPI is broken. repo will require a fix.

**Comment by fatahfd** [comment]
I Modify wapi script, its working bot sending and reply message
hopefully help
[wapi.zip](https://github.com/danielcardeenas/sulla/files/3884471/wapi.zip)

**Comment by smashah** [comment]
https://github.com/smashah/sulla/issues/12

**Comment by priteshpmehta** [comment]
> I Modify wapi script, its working bot sending and reply message
> hopefully help
> [wapi.zip](https://github.com/danielcardeenas/sulla/files/3884471/wapi.zip)

Hey @fatahfd your zip file works like charm. Could you please explain here, what exactly we have to do whenever there is such type of updates from web whatsapp?

Thank you for solution.

**Comment by danielcardeenas** [comment]
Please update
`npm i sulla@latest`
