### ISSUE TITLE
Sulla is getting -1 as ack

### ISSUE THREAD

**Issue by omalave** [danielcardeenas/sulla#152]
Hi!

I just testing this great library but I've a concern regarding ack value in the json response.

It's normal receive -1 as response?

![image](https://user-images.githubusercontent.com/3420419/69592736-e482b780-0fc4-11ea-9b81-3a1ae891eb64.png)

any idea?

**Comment by danielcardeenas** [comment]
Listen to event onAck:

```javascript
client.onAck((ack) => {
  console.log('Ack', ack);
})
```
