### ISSUE TITLE
No new messages Error

### ISSUE THREAD

**Issue by Michaelsafir** [danielcardeenas/sulla#158]
We have problem - sulla active, but no new messages come

**Comment by sagarsaini3993** [comment]
Hey @Michaelsafir , it would be great if you will use sulla-hotfix.

**Comment by ricardopereyra** [comment]
I have the same problem. What do you mean with use sulla-hotfix, @sagarsaini3993 ?

**Comment by sagarsaini3993** [comment]
Sulla have some bugs. Basically, SULLA HOTFIX is bug free. Just try it.

**Comment by gusbdev** [comment]
Hello @sagarsaini3993, thanks. Works for me.

**Comment by danielcardeenas** [comment]
Fixed in the new version. There are no bugs
