### ISSUE TITLE
IDK WHY I cant receive a message

### ISSUE THREAD

**Issue by cerolcs** [danielcardeenas/sulla#166]
I cant receive any message
![image](https://user-images.githubusercontent.com/35303121/70950506-96028f00-203f-11ea-9ff3-567a8481835e.png)

**Comment by gusbdev** [comment]
Hello @cerolcs, i had the same problem. See this https://github.com/danielcardeenas/sulla/issues/158. Just install "sulla-hotfix". Works for me.

**Comment by danielcardeenas** [comment]
Fixed in the new version
