### ISSUE TITLE
simulate that the bot is writing

### ISSUE THREAD

**Issue by chitogamer96** [danielcardeenas/sulla#167]
it would be very good feature!

**Comment by smashah** [comment]
@chitogamer96 You can do this with:

```javascript
Store.WapQuery.sendChatstateComposing('447123454354@c.us')
```

It's a bit slow though and it goes on for quite a while. So make sure you don't use this with your girlfriend :P

**Comment by danielcardeenas** [comment]
I'm about to add this feature as a public function. Wait for next release!

**Comment by danielcardeenas** [comment]
Super late tho, here it is:
```javascript
// chatId: '123123@c.us'
client.startTyping(chatId)
```
