### ISSUE TITLE
Loading QR Problem

### ISSUE THREAD

**Issue by OrhanArslan** [danielcardeenas/sulla#194]
Console waits on 'Loading QR' even tough I deleted session folder

**Comment by hsujon** [comment]
Same problem here. any update?

**Comment by vasani-arpit** [comment]
Yes. whatsapp has changed how they were showing QR code.

I think this issue will help 

https://github.com/vasani-arpit/WBOT/issues/85

**Comment by hsujon** [comment]
@vasani-arpit thanks for your clue. its working now.
just has to change
img[alt='Scan me!'] on line 79 and 82 in node_modules/sulla/dist/controllers/auth.js
to
canvas[role='img']

**Comment by danielcardeenas** [comment]
Just fixed this. Will update release in a moment
