### ISSUE TITLE
how to tag all members in group

### ISSUE THREAD

**Issue by gabrieru** [danielcardeenas/sulla#200]
Is possible to do it? anyone know a method to tag all members in the group. would be great if someone knows and show how to do it

**Comment by danielcardeenas** [comment]
This seems to be possible. Wait for next release

**Comment by danielcardeenas** [comment]
There are two methods for this task
Simple one:
```javascript
client.sendTextWithTags('0000@c.us', 'Hello @811334324 from sulla!')
```
