### ISSUE TITLE
Sulla do not detect already authenticated and hang

### ISSUE THREAD

**Issue by gnadelwartz** [danielcardeenas/sulla#201]
Using the example script:

On first start or after deleting 'session'  the example programm detects and show QR code.
After scanning QR code sending and recieving new messages is working

```
node dealwaecho.js
✔ Initializing whatsapp
ℹ Authenticate to continue
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄█▀▀▀█▀███▄█ ▄█  ▀ █▀▀ █ █ ▄▄▄▄▄ █
█ █   █ █ ▄█ ▄ ▄█▄█▄ ▀▀▀ █▄▀█ █▄█ █ █   █ █
█ █▄▄▄█ █▄ ███ ▀█ ▄█▀█ ████▄█▄ ▀▀██ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█▄█ █ ▀▄▀ █ █ █ █▄█▄▀▄█▄█▄▄▄▄▄▄▄█
█  ▄▄▀▀▄▀ ▀▄▄▀▀▄██ █▀▀▀▀ ▀▄▄ ▀▀  ▄▄▀█ ▄ ▀ █
...
██▄▄███▄▄▀▄█▀▄█▄▄ ▀ █▀ █▄█▄ ▀▀▀▄▄ ▄▄▄ █ ▀ █
█ ▄▄▄▄▄ ██▄▄  ▀ ▀██▀▀▄█▄ ▄▀█▀▀██▄ █▄█ ▄▄▄▀█
█ █   █ █▀▄▀▀ ▀█▀▀▀█▀▄▀▄▀ ▀▄▀ ▀▀▀  ▄▄▄███▄█
█ █▄▄▄█ █ ▄▀ █▄▀▀▀▄▀ █  ▀ ██▀█▄▀█ ██ █▄█▀██
█▄▄▄▄▄▄▄█▄█▄█▄██▄█▄▄▄██▄▄▄███▄█▄▄▄██▄█▄█▄██

✔ Authenticating
✔ Whatsapp is ready
```

On second start sulla hangs while detecing auth:

```
node dealwaecho.js
✔ Initializing whatsapp
ℹ Authenticate to continue
```

OS: Linux, OpenSuse 15.3
node:  v10.16.3

Any Ideas whats going wrong?

**Comment by danielcardeenas** [comment]
On it

**Comment by gnadelwartz** [comment]
> On it

sorry,  I don't unstand ...

**Comment by apriady** [comment]
Got same issue, and I think this is the problem :

<img width="802" alt="Screen Shot 2020-01-29 at 15 49 36" src="https://user-images.githubusercontent.com/1451429/73341327-02afb100-42af-11ea-97db-6f56e053a186.png">

**Comment by gnadelwartz** [comment]
hm, issue with chrome 49+ was reported as fixed in #162 by @danielcardeenas if I understand correctly... are you using the latest version of the lib?

**Comment by danielcardeenas** [comment]
Fixed on next release

**Comment by rfscheidt** [comment]
The problem keeps happening, it doesn't stay logged in. 
Does anyone have a way?

**Comment by gnadelwartz** [comment]
sorry to say, but I switched to sulla-hotfix ...

**Comment by danielcardeenas** [comment]
Install new version. Everything is fixed now

**Comment by egorky** [comment]
Hola, @danielcardeenas puedo confirmar que esto aún está ocurriendo y estoy utilizando la última versión. Mi sistema operativo es centOS 7.7.
```
[root@mx sulla]# npm list sulla
/root
└── sulla@2.3.5
[root@mx sulla]# npm version
{
  npm: '6.14.4',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '36.1',
  icu: '66.1',
  llhttp: '2.0.4',
  modules: '79',
  napi: '6',
  nghttp2: '1.40.0',
  node: '13.12.0',
  openssl: '1.1.1e',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.35.0',
  v8: '7.9.317.25-node.30',
  zlib: '1.2.11'
}
```
La primera vez que lo corres el proyecto funciona bien, puedo enviar mensajes y el bot me responde:
```
[root@mx sulla]# node app.js
⠋ Initializing whatsappChrome not found, using chromium
✔ Initializing whatsapp
ℹ Authenticate to continue
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ███▀ ▀▄▄█ ▄█▄█ █▄█ ███▄██ █ ▄▄▄▄▄ █
█ █   █ █▀▄██▀▀ ▄█▀ ▄▄▄█▄▀▀▄ ██▄▄██ █   █ █
█ █▄▄▄█ █▄▀  █▄ ▄ ▀██▄▄█▄▀▀ ▄ ▀█▄▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█ ▀▄█▄▀▄█ █ █▄█ █ █▄█▄▀▄█▄▄▄▄▄▄▄█
█▄ █▀█ ▄ ██▀▄█▀ ▄▄█▀ ██▄ ██▄██▄▄▀▄▀█▀  ▀███
█▄█▄█▄▄▄▄ █▀  █ ▄▄▄█▀▄█▀▀█▄█▄ █▄▀▄ ██ ██▀▀█
█▀▀▄▀█▀▄██▄▀█▀█   ▄█  ██▀████ ▄▀▀ ▄   ███▄█
█▄▄▄▀█ ▄█▄▀▀█▀▄▀▄ ▄▄█ ▄██▄▄▄▄▄▄ █ ███▀ ▀█▀█
███▀▄  ▄█▀▄█▀█ █ ▀▀▀█ ▄ ▄▄▄▀▄▀▄▄ ▀▀▀▄▀█▀▄▀█
██▀█▄██▄ ▀▄▀ ▀▄▀ ▄▄ ▄█▄▀  █▄ ██ ▄  ▀ ▀ ▄█▄█
█ ▄▀▄█ ▄ ██▄█▄▀▀███▀ ▄▄   ▀ ▄▄█▀█▄██    █ █
█▄▄▀▄ ▀▄▄▀ ▀ ▄▄  ▀▄██▀█▀███▀▄▄▄▄█ ▄█▄▀█▄▀██
█▄██  ▀▄ ▀ ▀▀▀▀█ ▀ █ ▀▀██▄▄█  ▀▄▄▀█   ▀█▄ █
█▀   █ ▄█▀▄▀▀▀  ▄█▄▀█▀█▀▀▀▄▄▄ ▄▀▀▄▀▄▄█▀ ▀▀█
█▀ ▄█▄ ▄▄█▄██▀▀▄▀▀█▀▄▀█▄ ▀█ ▄▀▄█▀▄██  ▀█▀▀█
█ ▄ ▄ █▄▀ ▄█▄▀█▄▄ ▄  ███▄▀█ ▄█▄█ ▄█▀██▀█▄▄█
█▄████▄▄█ ▀ ██▄  █████▀  ▄▀▄▀ ▄ ▀ ▄▄▄ ▀▀▄▀█
█ ▄▄▄▄▄ █ █▄█▄█▀ ▄▄▀█▀█ ▀ ██  ▄█▀ █▄█  ██▀█
█ █   █ ██▄ █▄▄ ▀█ ▀ █████▄▀  ▀▀ ▄ ▄▄▄▀ ▄██
█ █▄▄▄█ █▀▄▀ ▄█▄▄▄▄ ▀▀███▄██ ▄▄█▄ ▄▄█▄▄ ▄ █
█▄▄▄▄▄▄▄█▄██▄▄█▄████▄██▄███▄████▄██▄▄▄█▄███

✔ Authenticating
✔ Whatsapp is ready
^C
```
Si lo termino (enviando un control-c) y lo vuelvo a correr, nunca pasa de Authenticate to continue:
```[root@mx sulla]# node app.js
⠋ Initializing whatsappChrome not found, using chromium
✔ Initializing whatsapp
ℹ Authenticate to continue
^C
```

**Comment by danielcardeenas** [comment]
Pero el problema que tienes es que ahora? No funciona la librería o simplemente no recuerda tu sesión?

**Comment by robertsLando** [comment]
@danielcardeenas This happens to me too

**Comment by robertsLando** [comment]
This is the reason

![Schermata da 2020-04-09 16-48-39](https://user-images.githubusercontent.com/11502495/78908174-04051300-7a82-11ea-983a-9b151c49efec.png)

Seems that if latest session was closed without a valid auth the next time it is restored this is shown. Seems that it fails to set the user agent correctly

**Comment by danielcardeenas** [comment]
I'll add some scripts to detect updates on chrome and sulla to solve this

**Comment by imndr** [comment]
I've read that part but the session restoring feature is not working for me.

**Comment by danielcardeenas** [comment]
Okay I'll add a save localstorage feature so it gets recreated with all the tokens to force this fix. Give me a moment for the next release

**Comment by egorky** [comment]
> Pero el problema que tienes es que ahora? No funciona la librería o simplemente no recuerda tu sesión?

@danielcardeenas pienso que se trata de algún conflicto porque si no recordase mi sesión, debería pedirme autenticar nuevamente, sin embargo, ya no me pide autenticación simplemente se queda en el paso anterior a mostrarte el QR. La única forma de volver a funcionar es borrar todo el proyecto y volverlo a lanzar, ahí funciona todo pero solo la primera vez.

**Comment by egorky** [comment]
> First of all, looks like @egorky 's problem is not being able to save the session. This is a common problem in puppeteer when it gets interrupted without closing it correctly. Read [this part of the README](https://github.com/danielcardeenas/sulla/blob/master/README.md#closing-saving-sessions) to know how to handle it
> 
> Also, I'm adding right now update scripts to avoid @robertsLando and @apriady issue

@danielcardeenas I did read that part at the beginning, and at first I thought that that could be the problem, but, when I add that piece of code to my app.js I get an error (something about the ... part) and the project doesn't launch. I have to admit my next to none knowledge of JS. Anyway, thanks for the fast reply, I really appreciate it.

**Comment by danielcardeenas** [comment]
Gonna close this then.
