### ISSUE TITLE
Only works with existing contacts on chat tab

### ISSUE THREAD

**Issue by andretasty** [danielcardeenas/sulla#202]
I cant send messages for numbers that arent in my chat tab. The sulla only work when the number that im trying to send message is already on chat tab previously. What im doing wrong?

Here is my code: 

`const sulla = require('sulla');

sulla.create().then(client => start(client));

function start(client) {
      client.sendText('554499604289@c.us', '👋 Hello from sulla!');
}`

**Comment by robertsLando** [comment]
@andretasty Fixed in linked pr

**Comment by danielcardeenas** [comment]
To send a message to a non-added contact use sendMessageToId:
```javascript
client.sendMessageToId('123123123123@c.us', '👋 Hello from sulla!');
```
