### ISSUE TITLE
Using sulla as a REST API

### ISSUE THREAD

**Issue by iamshouvikmitra** [danielcardeenas/sulla#208]

**Comment by vasani-arpit** [comment]
doing `sulla.create()` is equivalent to 

1. Opening chrome 
2. opening WA
3. completing WA loading process until first screen shows up

This is very heavy task. you should not do it inside an endpoint. I suggest you to keep all these things ready before people start hitting your endpoint.

**Comment by iamshouvikmitra** [comment]
I am using something like such
```
const sulla = require("sulla");
sulla
  .create()
  .then(client => start(client))
  .catch(err => console.log(err));

function start(client) {
  app.post("/send", (req, res) => {
    let to = req.body.to;
    let message = req.body.message;
    if (to && message) {
      client
        .sendText(`${to}@c.us`, message)
        .then(response => res.json({ success: true, payload: response }))
        .catch(err =>
          res.json({ success: false, payload: err })
        );
    } else {
        res.json({success : false, payload: "Validation Error"})
    }
  });
}
```
Along with this, can someone tell me how can I send messages to numbers that are not in my contact list?
It seems sulla doesn't allows us to do that! Is there a work-around?

**Comment by vasani-arpit** [comment]
What is the error? Code seems right theoretically.

**Comment by iamshouvikmitra** [comment]
> What is the error? Code seems right theoretically.

Yup, it's working. I just posted it for other peoples. I guess we could close this issue! But could any body tell me how to message people those are not in my contact list? using something like using https://api.whatsapp.com/send?phone=+91XXXXXXXXXX

**Comment by mtuchi** [comment]
What does `@c.us` mean in this piece of code ?

> I am using something like such
> 
> ```
> const sulla = require("sulla");
> sulla
>   .create()
>   .then(client => start(client))
>   .catch(err => console.log(err));
> 
> function start(client) {
>   app.post("/send", (req, res) => {
>     let to = req.body.to;
>     let message = req.body.message;
>     if (to && message) {
>       client
>         .sendText(`${to}@c.us`, message)
>         .then(response => res.json({ success: true, payload: response }))
>         .catch(err =>
>           res.json({ success: false, payload: err })
>         );
>     } else {
>         res.json({success : false, payload: "Validation Error"})
>     }
>   });
> }
> ```
> 
> Along with this, can someone tell me how can I send messages to numbers that are not in my contact list?
> It seems sulla doesn't allows us to do that! Is there a work-around?

**Comment by MillesC** [comment]
@iamshouvikmitra 
Great solution.
It allowed me to create an initial user interface!

**Comment by MillesC** [comment]
> > Qual é o erro? Código parece correto teoricamente.
> 
> Sim, está funcionando. Acabei de publicar para outras pessoas. Acho que poderíamos fechar esse problema! Mas alguém poderia me dizer como enviar mensagens para pessoas que não estão na minha lista de contatos? usando algo como usar https://api.whatsapp.com/send?phone=+91XXXXXXXXXX

A problem I am realizing is that it only sends when the contact is present on the main screen of whatsapp.
If I delete the conversation, it doesn't send the message, even with the saved contact.

**Comment by danielcardeenas** [comment]
Just use sulla as you normally do on a server
