### ISSUE TITLE
Assigning labels to chat

### ISSUE THREAD

**Issue by tinyCoder32** [danielcardeenas/sulla#216]
Hi, after a deep search, using WA Business account, I reached the function that labels a specific chat, but I cold not find how to use it, I appreciate your kind help:

`Store.Label.addOrRemoveLabels`

**Comment by danielcardeenas** [comment]
I'll take a look

**Comment by robertsLando** [comment]
For reference:

WAPI
```js
/**
 * @param label: either the id or the name of the label. id will be something simple like anhy nnumber from 1-10, name is the label of the label if that makes sense.
 * @param objectId The Chat, message or contact id to which you want to add a label
 * @param type The type of the action. It can be either "add" or "remove"
 * @returns boolean true if it worked otherwise false
 */
window.WAPI.addOrRemoveLabels = async function (label, objectId, type) {
    var {id} = Store.Label.models.find(x=>x.id==label||x.name==label)
    var to = Store.Chat.get(objectId) || Store.Msg.get(objectId) || Store.Contact.get(objectId);
    if(!id || !to) return false;
    const {status} = await Store.Label.addOrRemoveLabels([{id,type}],[to]);
    return status===200;
}
```

Sulla API:
```js
/**
   * Adds label from chat, message or contact. Only for business accounts.
   * @param label: either the id or the name of the label. id will be something simple like anhy nnumber from 1-10, name is the label of the label if that makes sense.
   * @param id The Chat, message or contact id to which you want to add a label
   */
  public async addLabel(label: string, id: string) {
    return await this.page.evaluate(
      ({label, id}) => {WAPI.addOrRemoveLabels(label, id, 'add')},
      {label, id}
      )
  }

  /**
   * Removes label from chat, message or contact. Only for business accounts.
   * @param label: either the id or the name of the label. id will be something simple like anhy nnumber from 1-10, name is the label of the label if that makes sense.
   * @param id The Chat, message or contact id to which you want to add a label
   */
  public async removeLabel(label: string, id: string) {
    return await this.page.evaluate(
      ({label, id}) => {WAPI.addOrRemoveLabels(label, id, 'remove')},
      {label, id}
      )
  }
```

**Comment by smashah** [comment]
> For reference:
> 
> WAPI
> 
> ```js
> /**
>  * @param label: either the id or the name of the label. id will be something simple like anhy nnumber from 1-10, name is the label of the label if that makes sense.
>  * @param objectId The Chat, message or contact id to which you want to add a label
>  * @param type The type of the action. It can be either "add" or "remove"
>  * @returns boolean true if it worked otherwise false
>  */
> window.WAPI.addOrRemoveLabels = async function (label, objectId, type) {
>     var {id} = Store.Label.models.find(x=>x.id==label||x.name==label)
>     var to = Store.Chat.get(objectId) || Store.Msg.get(objectId) || Store.Contact.get(objectId);
>     if(!id || !to) return false;
>     const {status} = await Store.Label.addOrRemoveLabels([{id,type}],[to]);
>     return status===200;
> }
> ```
> 
> Sulla API:
> 
> ```js
> /**
>    * Adds label from chat, message or contact. Only for business accounts.
>    * @param label: either the id or the name of the label. id will be something simple like anhy nnumber from 1-10, name is the label of the label if that makes sense.
>    * @param id The Chat, message or contact id to which you want to add a label
>    */
>   public async addLabel(label: string, id: string) {
>     return await this.page.evaluate(
>       ({label, id}) => {WAPI.addOrRemoveLabels(label, id, 'add')},
>       {label, id}
>       )
>   }
> 
>   /**
>    * Removes label from chat, message or contact. Only for business accounts.
>    * @param label: either the id or the name of the label. id will be something simple like anhy nnumber from 1-10, name is the label of the label if that makes sense.
>    * @param id The Chat, message or contact id to which you want to add a label
>    */
>   public async removeLabel(label: string, id: string) {
>     return await this.page.evaluate(
>       ({label, id}) => {WAPI.addOrRemoveLabels(label, id, 'remove')},
>       {label, id}
>       )
>   }
> ```

@robertsLando if you're going to continue to copy-paste my work (along with the typos) at least link back to the source.

**Comment by robertsLando** [comment]
@smashah Your project is a fork of this so its also that a copy or not? :smile: Sorry if I didn't referenced your commits it was just easier to copy the code, @danielcardeenas could implement that in a different way that could be a starting point to discuss

**Comment by smashah** [comment]
Yes, it's easy to copy the code, and that part is 100% fine with me. It is just as easy to copy the source link which is the point of my previous comment. I accept your apology. Hopefully, you've learnt your lesson.

**Comment by robertsLando** [comment]
I have added the source link to your project, will edit the other comment in the other issue to :+1:

**Comment by danielcardeenas** [comment]
Chill guys imma close this. Looks like tinyCoder already has this figured it out.
