### ISSUE TITLE
listen changes in a group

### ISSUE THREAD

**Issue by xshion13** [danielcardeenas/sulla#225]
how can i add a listener in order to send messages when some event happens in a group. Specially if someone is added to the group, he entered via url, he got kicked, how can i send a custom message for each event? please help

**Comment by robertsLando** [comment]
Actually you can only listen to `onParticipantsChanged`

**Comment by xshion13** [comment]
> Actually you can only listen to `onParticipantsChanged`

but i dont know how to use it, can you explain please

**Comment by danielcardeenas** [comment]
`console.log` a message to see chatId field

```javascript
// chatId looks like this: '5518156745634-1516512045@g.us'
client.onParticipantsChanged(message.chatId, (event) => {
  console.log('Particiapnt change event', event);
});
```

This will log something like this:
```javascript
event {
  by: '000000000@c.us',
  action: 'leave',
  who: [ '000000000@c.us' ]
}
```

Event object interface is here: [ParticipantEvent](https://github.com/danielcardeenas/sulla/blob/master/src/api/model/participant-event.ts)
