### ISSUE TITLE
check if the number is a valid whatsapp number?

### ISSUE THREAD

**Issue by marcipriano** [danielcardeenas/sulla#227]
is it possible to check before sending if the number is a valid whatsapp number?
a confirmation must be sent to numbers of customers registered in the system. the client informs the whatsapp number there. however, as it is manual, typing errors can occur and validation to know if it is a number of whatsapp would decrease the possibility of blocking.
I checked the functions and I didn't identify any that can do that

**Comment by danielcardeenas** [comment]
Theres a method inside `retriever.layer.ts` https://github.com/danielcardeenas/sulla/blob/2eb2e7e1fbe842226b87fae4fbca21ce556d5041/src/api/layers/retriever.layer.ts#L196

```typescript
/**
 * Checks if a number is a valid whatsapp number
 * @param contactId, you need to include the @c.us at the end.
 * @returns contact detial as promise
 */
public async getNumberProfile(contactId: string) {
  return this.page.evaluate(
    (contactId) => WAPI.getNumberProfile(contactId),
    contactId
  );
}
```

```javascript
const profile = await client.getNumberProfile('0000000@c.us')
```
