### ISSUE TITLE
[HELP]  Step verification?

### ISSUE THREAD

**Issue by m4theus-dev** [danielcardeenas/sulla#228]
Hello good afternoon all right ?

Could you help me do some checks like that?
![image](https://user-images.githubusercontent.com/24884068/78592995-4af1cf00-781c-11ea-8395-728d6864575e.png)

I already have something in mind, but do you know of a better way to do it?

**Comment by danielcardeenas** [comment]
You need to save the state of the conversation for each contact you are chatting with. However this is not related to sulla but to some business logic

**Comment by m4theus-dev** [comment]
> You need to save the state of the conversation for each contact you are chatting with. However this is not related to sulla but to some business logic

Do you know if anyone has done something like this and has repo here on git?

**Comment by robertsLando** [comment]
It depends on the logic you are tring to create. Anyway you just should keep a reference to his latest questions/response in a db or in memory
