### ISSUE TITLE
Start a new conversation

### ISSUE THREAD

**Issue by douglasevaristo** [danielcardeenas/sulla#23]
Hi, i'm try to use but if the contact don't has a previews talk with me i cant start a new conversation. This is normal? Has plane for implementation this in the future?

**Comment by rgchurion** [comment]
Tengo la idea, pero infortunadamente nodejs es algo enredado para programar :-( , no he logrado que una función retorne el resultado de una consulta para que sea enviado al whatsapp de quien pregunta, a la línea que envía el mensaje a whatsapp llega "undefined" pero al sacarlo por console.log ahí si lo muestra. Estoy leyendo y viendo videos tutoriales sobre nodejs para entenderlo y crear funciones, crear bucles, consultas periódicas de tal forma que si en la BD hay un anuncio lo "recoja" y se lo envíe al whatsapp, pero hasta el momento nada que avanzo, muy diferente a php.

**Comment by kidstell** [comment]
please help, i am trying to use this project. where do i put the example code that was pasted in the README.md

**Comment by theonlyray** [comment]
> please help, i am trying to use this project. where do i put the example code that was pasted in the README.md
> 
> i just need a little push to understand how to implement custom code on top of this. i havetried using the index.ts but it fails. i also tried the index.js
> 
> ```
> const sulla = require('sulla');
> 
> sulla.create().then(client => start(client));
> 
> function start(client) {
>   client.onMessage(message => {
>     if (message.body === 'Hi') {
>       client.sendText(message.from, '👋 Hello from sulla!');
>     }
>   });
> }`
> ```

Create a file, example "index.js" copy the code and execute it in cmd "node index.js", then login with QR scan

**Comment by MuallimCh** [comment]
> Hi, i'm try to use but if the contact don't has a previews talk with me i cant start a new conversation. This is normal? Has plane for implementation this in the future?

I think just use:
`client.sendText("phone@c.us", "message");`

Which phone is in international format without + sign.

**Comment by brunominervino** [comment]
I got same problem, I can't open new conversation, just works in conversations on "conversation tab".

**Comment by fernandovaller** [comment]
Has anyone been able to send to a new contact?

**Comment by kaiserdj** [comment]
You can create a conversation with a phone number using the following url: https://web.whatsapp.com/send?phone=34601XXXXXX&text=message&source=&data=

**Comment by danielcardeenas** [comment]
Plase update to new version

To send a message to a contact (non-group) just type the number

```typescript
client.sendText('555555555555@c.us', 'Direct message');
```

On a regular message received do a `console.log(message)` to and check the `from` property

**Comment by Mrjavaci** [comment]
> Plase update to new version
> 
> To send a message to a contact (non-group) just type the number
> 
> ```ts
> client.sendText('555555555555@c.us', 'Direct message');
> ```
> 
> On a regular message received do a `console.log(message)` to and check the `from` property

THANK YOU FOR EVEVERYTHİNG
