### ISSUE TITLE
issue in centos 7 - missing libraries

### ISSUE THREAD

**Issue by xshion13** [danielcardeenas/sulla#236]
i tried to install it in centos 7 but got this message: 

![image](https://user-images.githubusercontent.com/56605018/78754213-bdf26700-793c-11ea-85ec-e33241cc86a0.png)

**Comment by robertsLando** [comment]
Try to follow this steps:

https://github.com/puppeteer/puppeteer/issues/391#issuecomment-483199554

Usually it could be some missing deps with chrome.

**Comment by danielcardeenas** [comment]
This looks like an environment issue:
Try also https://github.com/puppeteer/puppeteer/issues/391#issuecomment-324551649
