### ISSUE TITLE
Is it possible to use the Electron instance?

### ISSUE THREAD

**Issue by rafagouveia** [danielcardeenas/sulla#239]
I'm developing a client with Electron, where end users can log in to whatsapp and follow records without having much knowledge.

It's working really well, but I noticed that Sulla doesn't use the electron itself to instantiate.

My question is: Can I use Electron to instantiate a window with Whastsapp? if so, how? Or do I have to create a custom puppeteer?

**Comment by danielcardeenas** [comment]
That's interesting. Sulla right now usesa chrome instance. You will need to run sulla with headless option set to false and attach it to electron

**Comment by rafagouveia** [comment]
> That's interesting. Sulla right now usesa chrome instance. You will need to run sulla with headless option set to false and attach it to electron


When I set `headless= false`, opens the Chrome browser, what I hope is to open a window of Electron itself.

**Comment by robertsLando** [comment]
You should check this: https://github.com/puppeteer/puppeteer/issues/4655

——————

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by vasani-arpit** [comment]
If you are making an electron app then you can use it's webview control to do what sulla does with chrome instance. that way you will have user inactivity inside the app with having programmable control using [WAPI.js](https://github.com/danielcardeenas/sulla/tree/master/src/lib/wapi)

Using <webview /> tag control with `inject` attribute should do the trick.

**Comment by danielcardeenas** [comment]
I'm gonna close this issue since it's unrelated to sulla development. Feel free to continue with the discussion
