### ISSUE TITLE
Start session QRCode

### ISSUE THREAD

**Issue by m4theus-dev** [danielcardeenas/sulla#249]
I'm having trouble signing in ...
And only with me?

Every time I start the project it asks to scan the QRCode, but it does not appear to me

**Comment by danielcardeenas** [comment]
Show me your code

**Comment by m4theus-dev** [comment]
`const sulla = require('sulla');

sulla.create().then(client => start(client));

function start(client) {
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
    }
  });
}`
I was trying to use the example above but sometimes it happens ...
The first time I authenticate with you normally.
But for the second time this happens:
![image](https://user-images.githubusercontent.com/24884068/78952248-527ad780-7aab-11ea-8a3e-b761096fb801.png)

**Comment by m4theus-dev** [comment]
But now I am using this other example, and so far I have had no problems ...

``` js

const sulla = require ('sulla');
const fs = require ('fs');

const start = async () => {
   client = await sulla.create ('session-marketing', undefined, {
     headless: false,
     devtools: true,
     useChrome: true,
     debug: false
   });

   client.onMessage (message => {
     if (message.body === 'Hi') {
       client.sendText (message.from, '👋 Hello from sulla!');
     }
   });
   console.log ('Client ready');

};

start (); ```

**Comment by danielcardeenas** [comment]
Can you show me your sulla version?

**Comment by m4theus-dev** [comment]
sullaa@2.3.6



_@off topic
Do you have Discord?_

**Comment by danielcardeenas** [comment]
Update to new version **2.3.7** just in case.
I don't have Discord

**Comment by danielcardeenas** [comment]
I fuckd up, install 2.3.8
