### ISSUE TITLE
 sending data other than text

### ISSUE THREAD

**Issue by kusanagimilo** [danielcardeenas/sulla#25]
making tests to the library has worked correctly and I hope to continue working in this library, my question is if you can send images or video files or other data other than text.

**Comment by smashah** [comment]
@kusanagimilo https://github.com/smashah/sulla#sending-mediafiles

**Comment by danielcardeenas** [comment]
Use:
```
client.sendFile(chatId, 'path/to/file.mp4', 'file-title.mp4', 'This is a file');
```
Sulla will automatically decide the mime type and send it propery
