### ISSUE TITLE
client.UseHere() is not working..

### ISSUE THREAD

**Issue by nonna2010** [danielcardeenas/sulla#250]
i try use client.UseHere(); but not working please if anyone have same problem , report?

**Comment by danielcardeenas** [comment]
Show me your code

**Comment by nonna2010** [comment]
> Show me your code.
> 
> This is how it should be written
> 
> ```ts
> // State change
> client.onStateChange((state: SocketState) => {
>   console.log(state);
>   const conflits = [
>     sulla.SocketState.CONFLICT,
>     sulla.SocketState.UNPAIRED,
>     sulla.SocketState.UNLAUNCHED,
>   ];
>   if (conflits.includes(state)) {
>     client.useHere();
>   }
> });
> ```

thanks alot
