### ISSUE TITLE
sendFile not working with gif

### ISSUE THREAD

**Issue by robertsLando** [danielcardeenas/sulla#254]
Seems that sendFile sends gif as images and once downloaded they don't animate

**Comment by danielcardeenas** [comment]
I can confirm this is working, remember to use Chrome

**Comment by robertsLando** [comment]
It only send and image instead of an animated gif

——————

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by danielcardeenas** [comment]
Oh i realize now the issue. You are using `sendFile` let me fix it real quick

**Comment by danielcardeenas** [comment]
Whatsapp web does not supports sending plain gif images. To achieve this I need to convert the gif file into an mp4 and then sending it as a Whatsapp gif, however, this task requires the use of an external OS library `ffmpeg` which not every user have installed in their systems. I suggest converting your gif file into a mp4 outside from sulla and send it with a library like [this one](https://www.npmjs.com/package/videofy)
