### ISSUE TITLE
¿How to send messages from "sulla" to a contact?

### ISSUE THREAD

**Issue by rgchurion** [danielcardeenas/sulla#26]
First of all, my thanks to Daniel for such an excellent tool. Could someone please put an example on how to get a value from a mysql table, validate it if it is less than 12 that sends an alert to two or three contacts? It is a voltage monitoring. My thanks again.

**Comment by rgchurion** [comment]
At the moment I have a routine in PHP running every 10 minutes and if the value is less than 12 send emails and messages to telegram reporting the news if it is greater than 12 I do not do anything ..

**Comment by sberlati** [comment]
You can send a message using `sendText(number, 'Your message')`. 

I recommend you to previously **use the event onMessage() and add a console.log()** to see the message structure and the number format.

Using the **readme.md** example:
```javascript
import { create, Whatsapp } from 'sulla';

create().then(client => start(client));

function start(client: Whatsapp) {
  client.onMessage(message => {
    console.log(message); // Log the message structure
  });
}
```

In my case, the phone number "+54 911 1234-5678" (**international phone format**) is `5491112345678@c.us`.

After formatting your phone number correctly, you can send it a message by simply adding: 
```javascript
client.sendText("phone-number@c.us", "Your message");
```

**Comment by rgchurion** [comment]
@sberlati , Thanks very much!

**Comment by danielcardeenas** [comment]
Exactly how @sberlati said
```python
client.sendText("5211213123123@c.us", "Your message");
```
