### ISSUE TITLE
Issues with chatId

### ISSUE THREAD

**Issue by AlexanderPineda** [danielcardeenas/sulla#266]
chatId doesn't looks like this: '5518156745634-1516512045@g.us' it has a format similar as '5732284371138@c.us'

**Comment by robertsLando** [comment]
The first is a group chat id, the second is a contact chat id 

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by danielcardeenas** [comment]
Both are considered chat Ids.

**Comment by AlexanderPineda** [comment]
The issue is that when, I am gonna use the client.loadAndGetAllMessagesInChat(chatId); function, it returns an issue "(node:7160) UnhandledPromiseRejectionWarning: ReferenceError: client is not defined"

**Comment by AlexanderPineda** [comment]
@danielcardeenas 
There any way to see the outbound messages that I  sent to someone in the whatsapp, In this moment I can watch an store the inbound message. Could you explain me any method to obtain the outbound messages please. Thanks a lot

**Comment by AlexanderPineda** [comment]
I solve my issue, I was a mistake using the method
Thanks
