### ISSUE TITLE
getChatByContact

### ISSUE THREAD

**Issue by FelixWeichselgartner** [danielcardeenas/sulla#267]
Hi,
today I discovered your awesome library.
In the past i used selenium to automate whatsapp massages but now i want to switch to your framework.
So far i discovered how to get a contact from a phone number, now i would need to get the chat by the contact. In the documentation you always refer to chadId. Is there any way I can get the chadId from the contact? could not find anything here: https://github.com/danielcardeenas/sulla/tree/master/src/lib/wapi/functions
```
my contact:
{
  id: {
    server: 'c.us',
    user: '<phone_number>',
    _serialized: '<phone_number>@c.us'
  },
  name: '<name_of_contact>',
  shortName: '<name_of_contact>',
  pushname: '<name_of_contact>',
  type: 'in',
  isBusiness: false,
  isEnterprise: false,
  statusMute: false,
  labels: [],
  formattedName: '<name_of_contact>',
  isMe: false,
  isMyContact: true,
  isPSA: false,
  isUser: true,
  isWAContact: true,
  profilePicThumbObj: {
    id: {
      server: 'c.us',
      user: '<phone_number>',
      _serialized: '<phone_number>@c.us'
    },
    img: null,
    imgFull: null
  },
  msgs: null
}
```

TY for your help.
Greetings Felix

**Comment by robertsLando** [comment]
The chatid is the contact number + @c.us suffix

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by FelixWeichselgartner** [comment]
@robertsLando ty very much. 

I could just do:
```
await client.sendText("<phone_number>@c.us", '👋 Hello from sulla!');
```
without even getting the contact.

Maybe it would be a good idea to include this in https://github.com/danielcardeenas/sulla#Chatting.

Have a nice weekend!

**Comment by robertsLando** [comment]
Feel free to open a PR with fixed docs :)


---

Daniel - Software Engineer

Support me at:
    Github sponsors
