### ISSUE TITLE
Can someone tell me how to collect senders number

### ISSUE THREAD

**Issue by MintyWallpaper** [danielcardeenas/sulla#272]
The number i'm going to use will be public and need people to register; 
Of course it was easy enough to receive a message from anyone but to log the senders number or ID how is this possible? 

`if (msg === 'Register'){
    await client.sendText(message.from, " ---")
    /// Log users number to write to dB somehow

  }`

Thanks in advance

**Comment by MintyWallpaper** [comment]
Figured it out 
const user = await client.getNumberProfile(message.from);

if (msg === 'Register'){
await client.sendText(message.from, " ---")
console.log(user)
}

**Comment by danielcardeenas** [comment]
message.from
messafe.author (if group chat)
