### ISSUE TITLE
Promise { <pending> } when calling client.getGroupMembers

### ISSUE THREAD

**Issue by erkum** [danielcardeenas/sulla#315]
Hi,
I only get `Promise { <pending> }` when I call client.getGroupMembers().

Did I do something wrong?

```
const sulla = require('sulla');

sulla.create().then((client) => start(client));

function start(client) {

    client.onMessage((message) => {
        console.log(client.getGroupMembers('xxxxxxxx-xxxx@g.us'))
    });
}
```

**Comment by erkum** [comment]
> 
> 
> Hi,
> I only get `Promise { <pending> }` when I call client.getGroupMembers().
> 
> Did I do something wrong?
> 
> ```
> const sulla = require('sulla');
> 
> sulla.create().then((client) => start(client));
> 
> function start(client) {
> 
>     client.onMessage((message) => {
>         console.log(client.getGroupMembers('xxxxxxxx-xxxx@g.us'))
>     });
> }
> ```

**Comment by nonna2010** [comment]
const sulla = require('sulla');

sulla.create().then((client) => start(client));

async function start(client) {

    client.onMessage((message) => {
        console.log( await client.getGroupMembers('xxxxxxxx-xxxx@g.us'))
    });
}

**Comment by erkum** [comment]
I got it
I had to do it like this:

```
const sulla = require('sulla');

sulla.create().then((client) => start(client));

function start(client) {
    client.onMessage(async (message) => {
        const members = await client.getGroupMembers('491602127398-1564217417@g.us')
        console.log(members);Mz4TTKvUtAWe4
    });
}
```

thanks :)

**Comment by erkum** [comment]
I got it right now.
I had to do it like this:

```
const sulla = require('sulla');

sulla.create().then((client) => start(client));

function start(client) {
    client.onMessage(async (message) => {
        const members = await client.getGroupMembers('xxxxxx-xxxx@g.us')
        console.log(members);Mz4TTKvUtAWe4
    });
}
```

Thank you :)
