### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by rcarcasson** [danielcardeenas/sulla#32]
I installed the library following the steps but when I read the QR nothing happens: it doesn't open a tab on the browser or something.

Im using Windows, there's something else that I need to do to run correctly?

Regards and great work!

**Comment by joelemanoel** [comment]
It will not display any tabs or open the browser.
Just send a message to the number you are using containing "Hi" and you can test if it is working.

**Comment by rcarcasson** [comment]
Thanks @joelemanoel ! Now I understand how it works and IT WORKED!!! 👍 

Regards!!!
