### ISSUE TITLE
How to generate QR CODE to be used in browser?

### ISSUE THREAD

**Issue by developerdevice** [danielcardeenas/sulla#333]

**Comment by roelandp** [comment]
see the instruction in the README with alternative suggestion on how to output the QRcode as base64 encoded file. This file you could then open in the browser by storing it somewhere on a web-public-facing directory, with some refresher script on it pulling new versions. 

Personally I'm looking at pushing the binary blob via websocket to the client bot interface but thats because i've built my chatbot around a little interface working with asynchronous websocket.

**Comment by developerdevice** [comment]
> see the instruction in the README with alternative suggestion on how to output the QRcode as base64 encoded file. This file you could then open in the browser by storing it somewhere on a web-public-facing directory, with some refresher script on it pulling new versions.
> 
> Personally I'm looking at pushing the binary blob via websocket to the client bot interface but thats because i've built my chatbot around a little interface working with asynchronous websocket.

Thank you for your reply! I'm newbie about Sulla, my doubt is how can i do what you said.

**Comment by roelandp** [comment]
Im also a newbie to the apis written by Daniel, but he did a great job! 

Also the QRcode part is explained in a snippet: 
```
> create('sessionName', qrCallback, {
>   headless: true, // Headless chrome
>   devtools: false, // Open devtools by default
>   useChrome: true, // If false will use Chromium instance
>   debug: false, // Opens a debug session
>   logQR: true // Logs QR automatically in terminal
>   browserArgs: [''] // Parameters to be added into the chrome browser instance
>   refreshQR: 15000, // Will refresh QR every 15 seconds, 0 will load QR once. Default is 30 seconds
> });
```

Notice the qrCallback in the above sample. 

In another snippet in the readme you see the full qrCallback as a sample including how to treat the base64 encoded image blob and turn it into an image file even. 
https://github.com/danielcardeenas/sulla/blob/45e909d61afaf7abbeb1aba8a9a32d5798ff50a9/README.md#exporting-qr-code <https://github.com/danielcardeenas/sulla/blob/45e909d61afaf7abbeb1aba8a9a32d5798ff50a9/README.md#exporting-qr-code>

So it is literally explained over there. 

kr roeland
