### ISSUE TITLE
Is there a way for the API to be used in Electron?

### ISSUE THREAD

**Issue by amanharwara** [danielcardeenas/sulla#340]
Hello,

I am the maintainer of [Altus](https://github.com/amanharwara/altus) which is a client to use WhatsApp Web built using Electron. There are certain features from the API that would help me improve the experience in Altus. I was wondering, hence, whether there is a way to use the API inside Electron.

Any help would be appreciated. Thanks.

**Comment by camoreno765** [comment]
If in your code [Altus](https://github.com/amanharwara/altus) you can interact in a Backend way, then you can use Sulla, you just have to use the **npm i sulla** and use the characteristics provided by the project connecting with the actions of yours.
