### ISSUE TITLE
profilePicThumbObj is empty whereas current contact has a picture

### ISSUE THREAD

**Issue by rklf** [danielcardeenas/sulla#360]
As the title says, I've this number in my contact, I see his profile picture through web.whatsapp but profile pic object is empty. For some of my old contacts, ``profilePicThumbObj`` is not empty, I can access to the url. How can I deal with that ?

```{"id":{"server":"c.us","user":"##########","_serialized":"##########@c.us"},"name":"##########","type":"in","isBusiness":false,"isEnterprise":false,"statusMute":false,"sectionHeader":"#","labels":[],"formattedName":"##########","isMe":false,"isMyContact":true,"isPSA":false,"isUser":true,"isWAContact":true,"profilePicThumbObj":{},"msgs":null}```

Thanks!

**Comment by s2click** [comment]
the repository is deprecated use 

Install
npm i @s2click/venom
https://github.com/s2click/venom
