### ISSUE TITLE
Not Connected after read qrcode

### ISSUE THREAD

**Issue by vmcloudbr** [danielcardeenas/sulla#375]
please help me, after reading the sulla barcode on the connect, it started today in all our scripts

**Comment by CollapsedMetal** [comment]
Same here...

**Comment by thiagoamarante** [comment]
guys, I think it's discontinued here.
I use it, but I'm making all the corrections.
I can't merge

you have 2 options:
1 - use my branch - https://github.com/thiagoamarante/sulla/tree/develop
2 - use open-wa - https://github.com/open-wa/wa-automate-nodejs

**Comment by vmcloudbr** [comment]
> guys, I think it's discontinued here.
> I use it, but I'm making all the corrections.
> I can't merge
> 
> you have 2 options:
> 1 - use my branch - https://github.com/thiagoamarante/sulla/tree/develop
> 2 - use open-wa - https://github.com/open-wa/wa-automate-nodejs

i will change for your repository, thank you!

**Comment by vmcloudbr** [comment]
It worked!

**Comment by diegoacuario** [comment]
Como instalo desde consola amigos ayuda antes lo hacía con npm install –save sulla

**Comment by diegoacuario** [comment]
catchQR is not a function

**Comment by NabiilahDatabase** [comment]
> guys, I think it's discontinued here.
> I use it, but I'm making all the corrections.
> I can't merge
> 
> you have 2 options:
> 1 - use my branch - https://github.com/thiagoamarante/sulla/tree/develop
> 2 - use open-wa - https://github.com/open-wa/wa-automate-nodejs

sorry im noob, how to use your branch? to update my sulla

**Comment by vmcloudbr** [comment]
> > guys, I think it's discontinued here.
> > I use it, but I'm making all the corrections.
> > I can't merge
> > you have 2 options:
> > 1 - use my branch - https://github.com/thiagoamarante/sulla/tree/develop
> > 2 - use open-wa - https://github.com/open-wa/wa-automate-nodejs
> 
> sorry im noob, how to use your branch? to update my sulla

download the **develop** repository in https://github.com/thiagoamarante/sulla/tree/develop, not the **master** the link already takes to the **develop repository**, then unzip it on your machine, enter the folder and do an **npm install**, then run the **npm build** command, a **dist** folder will be created, copy the folder **DIST, NODE_NODULES, PACKAGE.JSON**, and replace it within your project at **node_modules / sulla**

**Comment by vmcloudbr** [comment]
> Como instalo desde consola amigos ayuda antes lo hacía con npm install –save sulla

> > guys, I think it's discontinued here.
> > I use it, but I'm making all the corrections.
> > I can't merge
> > you have 2 options:
> > 1 - use my branch - https://github.com/thiagoamarante/sulla/tree/develop
> > 2 - use open-wa - https://github.com/open-wa/wa-automate-nodejs
> 
> sorry im noob, how to use your branch? to update my sulla

download the **develop** repository in https://github.com/thiagoamarante/sulla/tree/develop, not the **master** the link already takes to the **develop repository**, then unzip it on your machine, enter the folder and do an **npm install**, then run the **npm build** command, a **dist** folder will be created, copy the folder **DIST, NODE_NODULES, PACKAGE.JSON**, and replace it within your project at **node_modules / sulla**

**Comment by vmcloudbr** [comment]
> guys, I think it's discontinued here.
> I use it, but I'm making all the corrections.
> I can't merge
> 
> you have 2 options:
> 1 - use my branch - https://github.com/thiagoamarante/sulla/tree/develop
> 2 - use open-wa - https://github.com/open-wa/wa-automate-nodejs
erro return LoginCanceled

**Comment by vmcloudbr** [comment]
(node:175080) UnhandledPromiseRejectionWarning: LoginCanceled
(node:175080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:175080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NabiilahDatabase** [comment]
thanks for ure help @vmcloudbr 

me too, i got an error LoginCanceled, I think the problem was here:

- src/controllers/initializer.ts
```
            result = await from(
              waPage
                .waitForFunction(
                  `
                  (document.getElementsByClassName('app')[0] &&
                  document.getElementsByClassName('app')[0].attributes &&
                  !!document.getElementsByClassName('app')[0].attributes.tabindex) || 
                  (document.getElementsByClassName('two')[0] && 
                  document.getElementsByClassName('two')[0].attributes && 
                  !!document.getElementsByClassName('two')[0].attributes.tabindex)
              `,
                  {
                    timeout: 20000,
                  }
                )
                .then(() => true)
                .catch(() => false)
            ).toPromise();
```

how fo fix it? @thiagoamarante

**Comment by brainwares** [comment]
> thanks for ure help @vmcloudbr
> 
> me too, i got an error LoginCanceled, I think the problem was here:
> 
>     * src/controllers/initializer.ts
> 
> 
> ```
>             result = await from(
>               waPage
>                 .waitForFunction(
>                   `
>                   (document.getElementsByClassName('app')[0] &&
>                   document.getElementsByClassName('app')[0].attributes &&
>                   !!document.getElementsByClassName('app')[0].attributes.tabindex) || 
>                   (document.getElementsByClassName('two')[0] && 
>                   document.getElementsByClassName('two')[0].attributes && 
>                   !!document.getElementsByClassName('two')[0].attributes.tabindex)
>               `,
>                   {
>                     timeout: 20000,
>                   }
>                 )
>                 .then(() => true)
>                 .catch(() => false)
>             ).toPromise();
> ```
> 
> how fo fix it? @thiagoamarante

use the original initializer.d.ts and initializer.js, build from original sulla-master

**Comment by vmcloudbr** [comment]
I managed to fix it, now we are going to open a new project using part of this one with more support the name of the repo will be Smile tomorrow so search

**Comment by chr0nu5** [comment]
Hey guys, to fix it, you have to use a mix of (in this order)

https://github.com/danielcardeenas/sulla/issues/375#issuecomment-639559717
and
https://github.com/danielcardeenas/sulla/issues/375#issuecomment-639986309

Run the first build from comment 1, and then, with another build from the sulla-master, copy the generated files to the develop build. Works fine here.

**Comment by vmcloudbr** [comment]
Yes is working, now creating new repository with name Venom, Starting support

**Comment by ahmadarif** [comment]
Nice @s2click :D

**Comment by s2click** [comment]
> Nice @s2click :D
Install
`npm i @s2click/venom`
https://github.com/s2click/venom

**Comment by diegoacuario** [comment]
[Grupo de apoyo de sulla de whatsapp](https://chat.whatsapp.com/CspaWC7R5iaGZs20MPecjT)

**Comment by rodrigoipe** [comment]
> npm i @s2click/venom

esse não funciona... da erro

**Comment by orkestral** [comment]
> > npm i @s2click/venom
> 
> esse não funciona... da erro

not @s2click is npm i venom-bot
