### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by diegocamy** [danielcardeenas/sulla#376]
Hi everyone. 

I'm facing a problem with my Heroku deploy.

Currently using this buildpack 
`https://github.com/heroku/heroku-buildpack-google-chrome.git`

And these are my create() options
`{
          headless: true, 
          devtools: false, 
          useChrome: true,
          debug: false, 
          logQR: true, 
          browserArgs: ['--no-sandbox'], 
          refreshQR: 15000},
        }`

I'm able to see the qr code on the Heroku console by executing
`heroku logs --tail -a myappname`

And I'm able to read the qr code with the phone, but after that nothing happens. The WhatsApp app on my phone tells me I have an active session and that's it.

Has anyone faced this issue? Am I doing something wrong?

Thank you

*edit: fixed the buildpack

**Comment by roelandp** [comment]
Their is an issue with the current state of Sulla available on NPM: 
Here are fixes: 
https://github.com/danielcardeenas/sulla/issues/375

**Comment by vmcloudbr** [comment]
> Hi everyone.
> 
> I'm facing a problem with my Heroku deploy.
> 
> Currently using this buildpack
> `https://github.com/heroku/heroku-buildpack-google-chrome.git`
> 
> And these are my create() options
> `{ headless: true, devtools: false, useChrome: true, debug: false, logQR: true, browserArgs: ['--no-sandbox'], refreshQR: 15000}, }`
> 
> I'm able to see the qr code on the Heroku console by executing
> `heroku logs --tail -a myappname`
> 
> And I'm able to read the qr code with the phone, but after that nothing happens. The WhatsApp app on my phone tells me I have an active session and that's it.
> 
> Has anyone faced this issue? Am I doing something wrong?
> 
> Thank you
> 
> *edit: fixed the buildpack

> > guys, I think it's discontinued here.
> > I use it, but I'm making all the corrections.
> > I can't merge
> > you have 2 options:
> > 1 - use my branch - https://github.com/thiagoamarante/sulla/tree/develop
> > 2 - use open-wa - https://github.com/open-wa/wa-automate-nodejs
> 
> sorry im noob, how to use your branch? to update my sulla

download the **develop** repository in https://github.com/thiagoamarante/sulla/tree/develop, not the **master** the link already takes to the **develop repository**, then unzip it on your machine, enter the folder and do an **npm install**, then run the **npm build** command, a **dist** folder will be created, copy the folder **DIST, NODE_NODULES, PACKAGE.JSON**, and replace it within your project at **node_modules / sulla**

**Comment by diegocamy** [comment]
I've decided to switch from sulla to open-wa, thank you for your kind answers! Have a good day.
