### ISSUE TITLE
How do I get contact photo from phone number?

### ISSUE THREAD

**Issue by foomoto** [danielcardeenas/sulla#38]
See the response given for the python framework here

https://github.com/danielcardeenas/whatsapp-framework/issues/26

**Comment by danielcardeenas** [comment]
This still is not implemented in this library. But it will be included in the next release

**Comment by foomoto** [comment]
Great, any idea when the next release is scheduled? @danielcardeenas

**Comment by danielct59** [comment]
Great, any idea when the next release is scheduled? @danielcardeenas

**Comment by robertsLando** [comment]
Just for reference: 

```js
window.WAPI.getProfilePicSmallFromId = function (id, done) {
    window.Store.ProfilePicThumb.find(id).then(function (d) {
        if (d.img !== undefined) {
            window.WAPI.downloadFileWithCredentials(d.img, done);
        } else {
            done(false);
        }
    }, function (e) {
        done(false);
    })
};

window.WAPI.getProfilePicFromId = function (id, done) {
    window.Store.ProfilePicThumb.find(id).then(function (d) {
        if (d.imgFull !== undefined) {
            window.WAPI.downloadFileWithCredentials(d.imgFull, done);
        } else {
            done(false);
        }
    }, function (e) {
        done(false);
    })
};

```

**Comment by foomoto** [comment]
> Just for reference:
> 
> ```js
> window.WAPI.getProfilePicSmallFromId = function (id, done) {
>     window.Store.ProfilePicThumb.find(id).then(function (d) {
>         if (d.img !== undefined) {
>             window.WAPI.downloadFileWithCredentials(d.img, done);
>         } else {
>             done(false);
>         }
>     }, function (e) {
>         done(false);
>     })
> };
> 
> window.WAPI.getProfilePicFromId = function (id, done) {
>     window.Store.ProfilePicThumb.find(id).then(function (d) {
>         if (d.imgFull !== undefined) {
>             window.WAPI.downloadFileWithCredentials(d.imgFull, done);
>         } else {
>             done(false);
>         }
>     }, function (e) {
>         done(false);
>     })
> };
> ```

Thanks.

How do i get the ID argument from phone number?

**Comment by robertsLando** [comment]
countryCode+number+”@c.us”

Example (italy contry code is 39)

390123456789@c.us

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by danielcardeenas** [comment]
Added it to the README:

```typescript
const url = await client.getProfilePicFromServer(chatId);
```
