### ISSUE TITLE
 Project Migration to Venom

### ISSUE THREAD

**Issue by orkestral** [danielcardeenas/sulla#385]
**for lack of support we migrated to a new Repository that already has updates**

[New Repo](https://github.com/orkestral/venom)

**Comment by foomoto** [comment]
New repo does not work

**Comment by s2click** [comment]
yes, here: https://github.com/orkestral/venom

**Comment by arthurhenrique** [comment]
A new one, for what?

**Comment by s2click** [comment]
> A new one, for what?


Hello, sulla is no longer updated, they migrated to the venom repo, where it is 100% working, follow the repo link: https://github.com/orkestral/venom

**Comment by s2click** [comment]
> A new one, for what?

or use this one that will not be updated anymore, just look at the readme at the end of what Daniel wrote in April, who could no longer update the Repo

**Comment by foomoto** [comment]
why not just maintain sulla guys since most of the code was ported there @s2click

**Comment by foomoto** [comment]
@danielcardeenas are you happy to add some new administrators?

**Comment by orkestral** [comment]
> @danielcardeenas are you happy to add some new administrators?

call, you don’t need to use venom, stay there, venom and another project now, and this one already has improvements that it didn’t have here, ask @danielcardeenas to put you as an admin here and you use your knowledge to help people, like never before I saw helping the people of this repo that all the problems were @s2click s2click that fixed it, if it doesn't help, it doesn't hurt.

**Comment by s2click** [comment]
exactly!

**Comment by foomoto** [comment]
@orkestral and @s2click i dont have any issue with Venom, actually tested it now and it works. Sulla worked for me some days ago, and I am wondering if a new project is what we need or this a minor fix that can be integrated to sulla.

**Comment by orkestral** [comment]
> @orkestral and @s2click i dont have any issue with Venom, actually tested it now and it works. Sulla worked for me some days ago, and I am wondering if a new project is what we need or this a minor fix that can be integrated to sulla.

we understand and like sula and @danielcardeenas , more like Wa Automate, who migrated from sulla and improved the solution itself with another view; we also have a vision of interesting things for the library, such as webhooks, remote imaging, improved location sending and many other resources that we are already working on, we count on your support to help us, this idea is for everyone and we will never charge for anything unlike Wa Automate, which charges shipping for unsubscribed contacts.

**Comment by foomoto** [comment]
I would love to support you guys, but you need more engineers on board. Is there documentation on how to develop for the project or taking a dive and cutting my teeth is the way?

**Comment by orkestral** [comment]
today we have **23 collaborators**, most were with @danielcardeenas  in this repository, we have our chat, where we create ideas and give suggestions:
https://chat.whatsapp.com/CMJYfPFqRyE2GxrnkldYED

**Comment by foomoto** [comment]
that's a good number. in the loop now.
