### ISSUE TITLE
Unable to authenticate user after first QR scan.

### ISSUE THREAD

**Issue by leostacowski** [danielcardeenas/sulla#40]
After the first time I scan the QR code, the application fails to authenticate my session, starting an endless loop to create a new QR and never continues, making me delete the 'session' folder in order to start it again every time, any help would be appreciated!

![Capturar](https://user-images.githubusercontent.com/29438415/61812103-3c43c300-ae19-11e9-89a6-b7ab9b4b4ebb.JPG)

**Comment by englishnow** [comment]
> 
> 
> After the first time I scan the QR code, the application fails to authenticate my session, starting an endless loop to create a new QR and never continues, making me delete the 'session' folder in order to start it again every time, any help would be appreciated!
> 
> ![Capturar](https://user-images.githubusercontent.com/29438415/61812103-3c43c300-ae19-11e9-89a6-b7ab9b4b4ebb.JPG)

Same thing here. I have to delete the session folder several times.

**Comment by mariomartinezsoto** [comment]
![image](https://user-images.githubusercontent.com/39411477/62341779-83355680-b4b2-11e9-8950-1035ae0b3085.png)

Meanwhile, I use it this way

**Comment by rishabhrpg** [comment]
`rm -r session && node index.js ` if you can't change the code

**Comment by smashah** [comment]
Everyone, if you want a temporary fix to this then please check out the change in the pull request. You need to update node_modules/sulla/dist/controllers/auth.js at line 67

from 

`        .waitForFunction("\n        document.getElementsByClassName('app')[0] &&\n        document.getElementsByClassName('app')[0].attributes &&\n        !!document.getElementsByClassName('app')[0].attributes.tabindex\n        ", {
`

to

`        .waitForFunction("document.getElementsByClassName('app')[0] && document.getElementsByClassName('app')[0].attributes && !!document.getElementsByClassName('app')[0].attributes.tabindex", {
`

**Comment by smashah** [comment]
If you're in a hurry please use this temporary fix until the PR is merged and released.

https://www.npmjs.com/package/sulla-hotfix

**Comment by OskJonsdottir** [comment]
In my case, the behaviour described above is due to this...

![shot3](https://user-images.githubusercontent.com/11447204/63447125-09b7d500-c46e-11e9-971c-40241fdfbbaf.png)

As suggested by @mariomartinezsoto and @rishabhrpg , deleting the session folder avoids the issue (but you lose the ability to start without scanning the QR code). @smashah hot fix doesn't help.

**Comment by OskJonsdottir** [comment]
Any idea what in the _session data_ may cause Whatsapp web behave as if your browser version was outdated? :thinking:

**Comment by smashah** [comment]
@oskjonsdottir Try editing line 9 on browser.ts then building. I will try this when I can.

**Comment by OskJonsdottir** [comment]
@smashah That's what I tried and it wouldn't work.

**Comment by UnKnoWn-Consortium** [comment]
Try changing the useragent string at line 9 of `controllers/browser.ts` at `src` and then rebuild or at line 55 of `controllers/browser.js` at `dist` to something else. The hard-coded one may have been flagged.

**Comment by smashah** [comment]
I've implemented puppeteer-extra-stealh onto sulla-hotfix (v.1.2.2) if you would like to give it a go. With my testing it seems to be working fine.
