### ISSUE TITLE
How to send message

### ISSUE THREAD

**Issue by rishabhrpg** [danielcardeenas/sulla#49]
```
// import { create, Whatsapp } from 'sulla';
const sulla = require('sulla');

sulla.create().then(client => start(client));

function start(client) {
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
      client.sendText("7895XXXXXX","hello");
    }
  });
}
```

This example only demonstrates how to reply to incoming messages but how to send messages without triggering client.onMessage ?

**Comment by Mrjavaci** [comment]
"message.from" is not just phone number. 
ex: 

`console.log(message.from)` 

read log and change number in string.

**Comment by rishabhrpg** [comment]
yes, it works after changing to number in the strings.
