### ISSUE TITLE
Image And Sound Message

### ISSUE THREAD

**Issue by Mrjavaci** [danielcardeenas/sulla#50]
when will you do image and sound feature ?

**Comment by luisflorido** [comment]
I've added image feature on #59

**Comment by Mrjavaci** [comment]
Thank you

**Comment by ramonck** [comment]
In the WAPI there's the following fuction for this that can be implemented:
`window.WAPI.sendImage = function (imgBase64, chatid, filename, caption, done) {
//var idUser = new window.Store.UserConstructor(chatid);
var idUser = new window.Store.UserConstructor(chatid, { intentionallyUsePrivateConstructor: true });
// create new chat
return Store.Chat.find(idUser).then((chat) => {
    var mediaBlob = window.WAPI.base64ImageToFile(imgBase64, filename);
    var mc = new Store.MediaCollection();
    mc.processFiles([mediaBlob], chat, 1).then(() => {
        var media = mc.models[0];
        media.sendToChat(chat, { caption: caption });
        if (done !== undefined) done(true);
    });
});
}`

**Comment by smashah** [comment]
https://github.com/smashah/sulla#sending-mediafiles

**Comment by danielcardeenas** [comment]
Sulla will take care automatically of the file types, just send it like this:

```javascript
// Send file (sulla will take care of mime types, just need the path)
await client.sendFile(chatId, 'path/to/file.pdf', 'cv.pdf', 'Curriculum');
```
