### ISSUE TITLE
QR Code does not work!

### ISSUE THREAD

**Issue by renato425** [danielcardeenas/sulla#519]
Hello everyone! Having connect the cellphone whatsapp to the QR Code that appears in the terminal. The problem is that even when I "authenticate" the Cell Phone in the QR Code, it is in the same message "Authenticate to continue"

Can someone help me?

Made with Google Translate

**Comment by marcelohead** [comment]
its happening for me too

**Comment by jaderesp** [comment]
> 
> 
> its happening for me too

Olá amigo, este projeto foi descontinuado, está desatualizado.

**Comment by Bautista-Baiocchi-lora** [comment]
> > its happening for me too
> 
> Olá amigo, este projeto foi descontinuado, está desatualizado.

Is there any working branches?

**Comment by danielcardeenas** [comment]
Fixed
