### ISSUE TITLE
Not able to scan QR code

### ISSUE THREAD

**Issue by omkar1707** [danielcardeenas/sulla#6]
The QR code on the terminal is scattered. No QR code reader is able to scan it.

**Comment by danielcardeenas** [comment]
This depends on your terminal. Try scanning with a dark background:
![image](https://user-images.githubusercontent.com/2654812/59472985-f9e49a80-8e05-11e9-91fb-0525c6809765.png)

**Comment by galbenyosef** [comment]
> This depends on your terminal. Try scanning with a dark background:
> ![image](https://user-images.githubusercontent.com/2654812/59472985-f9e49a80-8e05-11e9-91fb-0525c6809765.png)

Helped in my case.
