### ISSUE TITLE
get number connected

### ISSUE THREAD

**Issue by phenriquec** [danielcardeenas/sulla#616]
how to get the number of the connected whatsapp?

**Comment by vasani-arpit** [comment]
There is a function which is called `getMe()` which is written here 
https://github.com/danielcardeenas/sulla/blob/master/src/lib/wapi/wapi.js#L216

I am not sure it is working or not. I haven't used it.

**Comment by dahanj95** [comment]
@vasani-arpit I tried getMe with your wapi script and another and it doesn't work, can you fix it? I need it badly.

**Comment by vasani-arpit** [comment]
@dahanj95 try this https://github.com/vasani-arpit/WBOT/blob/master/src/WAPI.js it should work.

**Comment by dahanj95** [comment]
> @dahanj95 try this https://github.com/vasani-arpit/WBOT/blob/master/src/WAPI.js it should work.

That's the one I tried, doesn't work.
