### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by cerolcs** [danielcardeenas/sulla#64]
plz where is the functions, events, docs?

**Comment by smashah** [comment]
Please check src/api/WhatsApp.ts for available functions. It's prey simple for now but largely does what it says on the tin. @cerolcs

**Comment by Mrjavaci** [comment]
if you use phpstorm you can learn more about "sulla".

**Comment by danielcardeenas** [comment]
Im about to write a Wiki page for the repo!

**Comment by danielcardeenas** [comment]
Check out README file
