### ISSUE TITLE
WAPI.loadEarlierMessagesTillDate enters infinite loop if the earliest message is posterior to the requested time

### ISSUE THREAD

**Issue by OskJonsdottir** [danielcardeenas/sulla#66]
Current implementation of loadEarlierMessagesTillDate is

```
window.WAPI.loadEarlierMessagesTillDate = function (id, lastMessage, done) {
    const found = WAPI.getChat(id);
    x = function () {
        if (found.msgs.models[0].t > lastMessage) {
            found.loadEarlierMsgs().then(x);
        } else {
            done();
        }
    };
    x();
};
```

This tries to retrieve earlier messages even if the chat doesn't have any, which may cause an infinite loop. The fix would be something in the lines of:

```
window.WAPI.loadEarlierMessagesTillDate = function (id, lastMessage, done) {
    const found = WAPI.getChat(id);
    x = function () {
        if (found.msgs.models[0].t > lastMessage && !found.msgs.msgLoadState.noEarlierMsgs) {
            found.loadEarlierMsgs().then(x);
        } else {
            done();
        }
    };
    x();
};
```

**Comment by Theblood** [comment]
@OskJonsdottir  Hi, I'm testing with about 385 groups of whatsapp to see the behavior

**Comment by smashah** [comment]
@OskJonsdottir You should suggest this change in this repo:
https://github.com/mukulhase/WebWhatsapp-Wrapper
as the wapi.js is taken from here:
https://github.com/mukulhase/WebWhatsapp-Wrapper/blob/master/webwhatsapi/js/wapi.js

**Comment by Theblood** [comment]
@OskJonsdottir Excellent, your solution has worked correctly, it has been added in my repository and also in this repository.
https://github.com/Theblood/Wapi_NEW/blob/master/wapi.js

**Comment by rubenfaria** [comment]
I'm getting this error:
`Error: Evaluation failed: TypeError: done is not a function`

Despite the error, execution continues and the messages are loaded as expected.
Would someone give ideas on how to fix it?

**Comment by OskJonsdottir** [comment]
So apparently someone fixed 

> I'm getting this error:
> `Error: Evaluation failed: TypeError: done is not a function`
> 
> Despite the error, execution continues and the messages are loaded as expected.
> Would someone give ideas on how to fix it?

It sounds like you're not passing a function as the third argument?

**Comment by OskJonsdottir** [comment]
@danielcardeenas Apparently someone fixed this is the original repo now....

**Comment by smashah** [comment]
@OskJonsdottir https://github.com/smashah/sulla/blob/master/src/lib/wapi.js#L491
