### ISSUE TITLE
[Question] CRM integrations

### ISSUE THREAD

**Issue by brauliobo** [danielcardeenas/sulla#683]
Do you have any or a list of CRM software that Sulla can be integrated into?

I'd like to have a UI to manage multiple conversations via multiple attendants

**Comment by brauliobo** [comment]
Or maybe even through https://github.com/sigalor/whatsapp-web-reveng ?

**Comment by vasani-arpit** [comment]
have you tried this https://github.com/mauricioribeiro/Whatsapp-WEB ?

**Comment by brauliobo** [comment]
@vasani-arpit it seems outdated and not being used by many. any other options?

**Comment by vasani-arpit** [comment]
A quick PWA can be made easily for this with express + socket.io. as a wrapper around sulla. For admin UI, Can use Appsmith to make it fast and quick. for Integrations, can deploy a small n8n instance which will enable 250+ integration on top of sulla/WA. all this can be deployed into a server which can hardly cost $30 per month. Entire thing should be done couple of weeks including testing. 

There are several caveats into this. Should we take this discussion one-on-one?

**Comment by brauliobo** [comment]
I ended up using RocketChat + Venon + Node.js integration https://www.youtube.com/watch?v=BvM0iIZqFYk

Although I would like to have a more Whatsapp Web like interface, as the Rocket chat interface isn't really that good
