### ISSUE TITLE
instalación 

### ISSUE THREAD

**Issue by armandochavez** [danielcardeenas/sulla#69]
hola te felicito por tu proyecto.
pero tengo una consulta 
no puedo instalar el proyecto ayúdame con los pasos por favor.
![image](https://user-images.githubusercontent.com/15861958/63707496-a32d1100-c7f7-11e9-8fde-306c4af76773.png)

**Comment by MuallimCh** [comment]
> ![image](https://user-images.githubusercontent.com/15861958/63866518-ef538f00-c978-11e9-970e-4995236d1c98.png)
> esto me sale si pongo el npm install sulla

1. Create Empty Folder and cd to it
2. `npm init`
3. `npm install sulla`

The rest just create index.js as mentioned in this github main page (readme.md).
