### ISSUE TITLE
Developer Project

### ISSUE THREAD

**Issue by Mrjavaci** [danielcardeenas/sulla#85]
How To Compile project not using "npm i sulla". I prefer using "git clone"

**Comment by smashah** [comment]
you could just use ts-node with everything in src folder or just run ```npm run build``` and use everything in dist folder.

**Comment by armandochavez** [comment]
I did not understand you, please explain  smashah

**Comment by smashah** [comment]
git clone the repo.
Cd into the repo
npm i
npm run build
Copy dist folder
Paste into your project
Success

**Comment by armandochavez** [comment]
I get that error


![image](https://user-images.githubusercontent.com/15861958/65801840-a93c4780-e13f-11e9-889e-cd201123802c.png)

folder 
![image](https://user-images.githubusercontent.com/15861958/65801868-c113cb80-e13f-11e9-8928-4ce3d5616b79.png)
 code 
![image](https://user-images.githubusercontent.com/15861958/65801885-ccff8d80-e13f-11e9-9182-9fd9b875ef8d.png)

**Comment by danielcardeenas** [comment]
Clone project:

Execute following:
```sh
npm run build
npm run start
```
