### ISSUE TITLE
How to Send Messages into a group?

### ISSUE THREAD

**Issue by TKFRvisionOfficial** [danielcardeenas/sulla#89]
This would be my main application anyways so I just want to know if and if yes how its possible to do this. This in combination with media sending and recieving witch is hopfully on its way would make the perfect WhatsApp-Bot.

**Comment by fastsyrup** [comment]
bump

**Comment by TKFRvisionOfficial** [comment]
Any updates?

**Comment by amajai** [comment]
bump

**Comment by greenimpala** [comment]
The API is documented in the code:

https://github.com/danielcardeenas/sulla/blob/master/src/api/whatsapp.ts

Basing it from the README example, you might want to log all your groups... 

```js
async function start(client) {
    const groups = await client.getAllGroups()
    console.log(JSON.stringify(groups))
}
```

Find the serialized ID of the group that you want, found at path `group.contact.id._serialized`. Will look something like `123456789123-1234567891@g.us`.

Now send messages to your group:

```
client.sendText('123456789123-1234567891@g.us', 'test message')
```

**Comment by amajai** [comment]
@greenimpala Thanks alot!

**Comment by TKFRvisionOfficial** [comment]
> The API is documented in the code:
> 
> https://github.com/danielcardeenas/sulla/blob/master/src/api/whatsapp.ts
> 
> Basing it from the README example, you might want to log all your groups...
> 
> ```js
> async function start(client) {
>     const groups = await client.getAllGroups()
>     console.log(JSON.stringify(groups))
> }
> ```
> 
> Find the serialized ID of the group that you want, found at path `group.contact.id._serialized`. Will look something like `123456789123-1234567891@g.us`.
> 
> Now send messages to your group:
> 
> ```
> client.sendText('123456789123-1234567891@g.us', 'test message')
> ```

For now this seems to be the solution! Need to test that but seems legit...because I dont have so much time right now I will close this issue...

**Comment by TKFRvisionOfficial** [comment]
Thx alot btw
