### ISSUE TITLE
Downloading media (decrypting)

### ISSUE THREAD

**Issue by btursynb** [danielcardeenas/sulla#9]
Hi,
is there a chance that you will add this feature anytime soon?
p.s. - love ur project xD

**Comment by danielcardeenas** [comment]
Yes, I'm working on it
Thanks

**Comment by alejandroguille** [comment]
Hi, is it possible to download files?

**Comment by smashah** [comment]
@danielcardeenas what is the plan for implementation? Any way I can help move this forward? I just need some direction regarding how.

**Comment by smashah** [comment]
@btursynb @alejandroguille I worked on it a bit, please try and let me know if it worked for you via latest version of [sulla-hotfix](https://www.npmjs.com/package/sulla-hotfix).

https://github.com/smashah/sulla#decrypting-media

**Comment by danielcardeenas** [comment]
Here it is:
```javascript
import fs = require('fs');
import mime = require('mime-types');

client.onMessage(async (message) => {
  if (message.isMedia) {
    const buffer = await client.downloadFile(message);
    // At this point you can do whatever you want with the buffer
    // Most likely you want to write it into a file
    const fileName = `some-file-name.${mime.extension(message.mimetype)}`;
    fs.writeFile(fileName, buffer, function (err) {
      ...
    });
  }
});
```

**Comment by roysG** [comment]
It Stack on the line:
 const buffer = await client.downloadFile(message);

The await is not released
