### ISSUE TITLE
Developer Project clone

### ISSUE THREAD

**Issue by armandochavez** [danielcardeenas/sulla#97]
hola como hago que funcione este proyecto solo clonar y instalar

ya que si solo pongo el npm i sulla y lo llamo me ejecuta todo pero  entonces es por gusto que clone este proyecto.

como yo puedo ejecutar ese repositorio sin usar npm i sulla ya que es lo mismo y lo envía a node_modules pero no entiendo porque no me coge

**Comment by danielcardeenas** [comment]
Descarga el proyecto.
Ejecuta en terminal:

```bash
npm run build
npm run start
```
